parameters:
  # Default values
  useVersionSuffix: true

steps:
  # Package nugets
  - script: dotnet pack --configuration $(buildConfiguration) --version-suffix $(build.buildNumber) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration) with version suffix'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'true'))

  - script: dotnet pack --configuration $(buildConfiguration) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration)'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'false'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NuGet Packages'
    inputs:
      pathtoPublish: '$(Build.artifactStagingDirectory)/packages'
      artifactName: 'NuGet Packages'