parameters:
  # Default values
- name: useVersionSuffix
  type: boolean
  default: true
  displayName: 'If true, the build number will be added as or to the existing version suffix'
- name: versionSuffix
  type: string
  default: '' 
  displayName: 'If not empty, the version suffix will be used for packaging'
- name: artifactName
  type: string 
  default: 'NuGetPackages'
  displayName: 'Name of the artifact to package'
- name: codeSignerCertificate
  type: string
  default: ''
  displayName: 'The code signing certificate to use for signing the nuget packages'
- name: codeSignerPassword
  type: string
  default: ''
  displayName: 'Password for the code signing certificate'
- name: packageSolutionFile
  type: string
  default: ''
  displayName: 'Solution file to package. If empty, the default solution file in the working directory will be used'
- name: certificateProfileName
  type: string
  default: ''
  displayName: 'Certificate profile name in Trusted Signing'
- name: trustedSigningAccountEndpoint
  type: string
  default: ''
  displayName: 'Azure Trusted Signing account endpoint URL (e.g., https://eus.codesigning.azure.net)'
- name: trustedSigningAccountName
  type: string
  default: ''
  displayName: 'Trusted Signing account name'
- name: azureServiceConnection
  type: string
  default: ''
  displayName: 'Azure service connection for signing with Trusted Signing'

steps:
  - powershell: |
      [string] $versionSuffix = '${{ parameters.versionSuffix }}'
      [string] $addBuildNumber = '${{ parameters.useVersionSuffix }}'
      
       Write-Host "Add Build Number: $addBuildNumber"

      if ([string]::IsNullOrEmpty($versionSuffix) -and $addBuildNumber -eq 'true') 
      {
        $versionSuffix = $env:BUILD_BUILDNUMBER
      }
      
      Write-Host "Version Suffix: $versionSuffix"
      Write-Host "##vso[task.setvariable variable=VersionSuffixPackage;]$versionSuffix"
    displayName: 'Retrieve version suffix for packaging'

  - powershell: |    
      Write-Host "Determining if version suffix should be used"
      
      [string]$useVersionSuffix = 'true'
      [string]$versionSuffix = '$(VersionSuffixPackage)'

      Write-Host "Version Suffix: $versionSuffix"

      if ([string]::IsNullOrEmpty($versionSuffix)) 
      {
        $useVersionSuffix = 'false'
      }
      
      Write-Host "Use Version Suffix: $useVersionSuffix"
      Write-Host "##vso[task.setvariable variable=UseVersionSuffix;]$useVersionSuffix"
    displayName: 'Determine version suffix use for packaging'

  # Package nugets
  - script: dotnet pack ${{ parameters.packageSolutionFile }} --no-build --configuration $(buildConfiguration) --version-suffix $(VersionSuffixPackage) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration) with version suffix'
    condition: and(succeeded(), eq(variables.UseVersionSuffix, 'true'))

  - script: dotnet pack ${{ parameters.packageSolutionFile }} --no-build --configuration $(buildConfiguration) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration)'
    condition: and(succeeded(), eq(variables.UseVersionSuffix, 'false'))

  - ${{ if parameters.certificateValue }}: # Only sign if a code signing certificate is provided
    - template: codesign-nuget-packages.yml
      parameters:
        certificateValue: ${{ parameters.codeSignerCertificate }}
        certificatePasswordValue: ${{ parameters.codeSignerPassword }}
        packagePaths: $(Build.ArtifactStagingDirectory)\packages\*.nupkg
  - ${{ else if parameters.trustedSigningAccountEndpoint }}: # Only sign if Trusted Signing endpoint is provided
    - template: codesign-nuget-package-using-trusted-signing.yml
      parameters:
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        trustedSigningAccountEndpoint: ${{ parameters.trustedSigningAccountEndpoint }}
        trustedSigningAccountName: ${{ parameters.trustedSigningAccountName }}
        certificateProfileName: ${{ parameters.certificateProfileName }}
        packagePaths: $(Build.ArtifactStagingDirectory)\packages\*.nupkg
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(Build.artifactStagingDirectory)/packages'
      artifactName: ${{ parameters.artifactName }}