# Repo: FirelyTeam/azure-pipeline-templates
# File: scanDockerImage.yml
# Description: scan an docker image for vulnerabilities

parameters: 
- name: 'dockerRegistryConnection'
  type: 'string'
  displayName: 'The Azure Docker Registry connection'
- name: 'dockerRegistryName'
  type: 'string'
  displayName: 'The name of the Docker registry, like firely.azure.io'
- name: 'dockerImageRepoName'
  type: 'string'
  displayName: 'The name of the Docker repository, like firely/server'
- name: 'dockerImageRepoVersion'
  type: 'string'
  displayName: 'The version of the Docker repository'
- name: 'trivyIgnoreFile'
  type: 'string'
  default: ''
  displayName: 'The version of the Docker repository' 
- name : trivyCacheAzureSubscription
  type: string
  default: ''
  displayName: 'Subscription used to retrieve Trivy cache. If left empty, no cache will be used.'
- name : trivyCacheStorageAccount
  type: string
  default: ''
  displayName: 'Storage account name where the Trivy cache is stored'
- name: dockerhubRegistryConnection
  type: string
  default: ''
  displayName: 'The Docker Hub registry connection (required for scanning the image with docker scout)'


jobs:
- job: scanDockerImage
  displayName: Scan Docker image for vulnerabilities
  variables:
    - name: run_docker_scout
      value: $[ ne('${{ parameters.dockerhubRegistryConnection }}', '') ]
    - name: docker_image_full_name
      value: ${{ parameters.dockerRegistryName }}/${{ parameters.dockerImageRepoName }}:${{ parameters.dockerImageRepoVersion }}
    - name: docker_image_package_url
      value: pkg:docker/${{ parameters.dockerRegistryName }}/${{ parameters.dockerImageRepoName }}@${{ parameters.dockerImageRepoVersion }}

  steps:
  - checkout: self

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.dockerRegistryConnection }}

  - task: Bash@3
    displayName: 'Pull Docker image from private registry'
    inputs:
      targetType: inline
      script: |
        docker pull ${{ variables['docker_image_full_name'] }}

  - task: Docker@2
    displayName: Login to Docker Hub
    condition: and(succeeded(), eq(variables['run_docker_scout'], 'true'))
    inputs:
      command: login
      containerRegistry: ${{ parameters.dockerhubRegistryConnection }}
      
  - task: PowerShell@2
    displayName: "Convert trivyignore.txt to OpenVEX file"
    condition: and(succeeded(), eq(variables['run_docker_scout'], 'true'))
    inputs:
      targetType: inline
      script: |
        param()

        $TrivyIgnoreFile = "$(trivyIgnoreFile)"
        $OutputFile      = "vex.json"
        $Author          = "devops@fire.ly"
        $ProductPurl     = "$(docker_image_package_url)"

        Write-Host "Converting trivyignore → OpenVEX"
        Write-Host "Input: $TrivyIgnoreFile"
        Write-Host "Output: $OutputFile"

        if (-not (Test-Path $TrivyIgnoreFile)) {
            Write-Error "ERROR: $TrivyIgnoreFile not found!"
            exit 1
        }

        # RFC3339 timestamp
        $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:sszzz")
        $vexId = "https://openvex.dev/docs/public/vex-" + ([guid]::NewGuid().ToString().ToLower())

        $statements = @()
        $today = Get-Date

        Get-Content $TrivyIgnoreFile | ForEach-Object {
            $line = $_.Trim()
            if ($line -eq "" -or $line.StartsWith("#")) { return }

            $CVE = $line.Split(" ")[0].Trim()

            $Expiry = $null
            if ($line -match "exp:(\d{4}-\d{2}-\d{2})") {
                $Expiry = $Matches[1]
            }

            if ($Expiry) {
                $expiryDate = Get-Date $Expiry

                if ($expiryDate -lt $today) {
                    $Status = "affected"
                    $Justification = "no_known_fix"
                    $Impact = "Ignore period expired on $Expiry"
                }
                else {
                    $Status = "not_affected"
                    $Justification = "no_known_fix"
                    $Impact = "Ignored via .trivyignore migration (expires on $Expiry)"
                }
            }
            else {
                $Status = "not_affected"
                $Justification = "no_known_fix"
                $Impact = "Ignored via .trivyignore migration"
            }

            $stmtTs = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:sszzz")

            $stmt = @{
                vulnerability = @{ name = $CVE }
                timestamp = $stmtTs
                products = @(@{ "@id" = $ProductPurl })
                status = $Status
                justification = $Justification
                impact_statement = $Impact
            }

            $statements += $stmt
        }

        $document = @{
            "@context" = "https://openvex.dev/ns/v0.2.0"
            "@id" = $vexId
            author = $Author
            timestamp = $timestamp
            version = 1
            statements = $statements
        }

        $document | ConvertTo-Json -Depth 10 | Out-File -Encoding utf8 -FilePath $OutputFile

        Write-Host "OpenVEX file created: $OutputFile"
        Write-Host "Printing vex.json:"
        Write-Host "----------------------------------------"
        Get-Content $OutputFile | Write-Host
        Write-Host "----------------------------------------"  

  - task: CmdLine@2
    displayName: Run docker scout on image
    condition: and(succeeded(), eq(variables['run_docker_scout'], 'true'))
    inputs:
      script: |
        # Install the Docker Scout CLI
        echo "DOCKER_CONFIG=${DOCKER_CONFIG}"
        install_dir="$DOCKER_CONFIG/cli-plugins"
        echo "Installing Docker Scout CLI to ${install_dir}"
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b ${install_dir}
        echo "Get a CVE report for the base image"
        docker scout cves --vex-location vex.json --only-base ${{ variables['docker_image_full_name'] }} --exit-code --only-severity critical,high,medium,low 
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found in packages installed in the base image"
        else
          echo "No vulnerabilities found in packages installed in the base image"
        fi
        echo "Get a CVE report for the built image (without considering CVE from base image) "
        docker scout cves --vex-location vex.json --ignore-base ${{ variables['docker_image_full_name'] }} --exit-code --only-severity critical,high,medium,low 
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found in packages installed in the image"
        else
          echo "No vulnerabilities found in packages installed in the image"
        fi

  - template: ./scanWithRetryTask.yml
    parameters:
      dockerExtraArguments: ""
      trivyExtraArguments: "image ${{ variables['docker_image_full_name'] }}"
      trivyIgnoreFile: ${{ parameters.trivyIgnoreFile }}
      displayName: Scan image with Trivy
      trivyCacheAzureSubscription: ${{ parameters.trivyCacheAzureSubscription }}
      trivyCacheStorageAccount: ${{ parameters.trivyCacheStorageAccount }}
      localTrivyCachePath: $(Agent.TempDirectory)/trivy-cache

#  The Trivy task does not work yet.
#    - task: trivy@1
#      displayName: Scan image with Trivy
#      inputs:
#        image: ${{ parameters.dockerRegistryName }}/${{ parameters.dockerImageRepoName }}:${{ parameters.dockerImageRepoVersion }}
