# Repo: FirelyTeam/azure-pipeline-templates
# File: updateHelmChart.yml

parameters:
  - name: helmRepoId
    type: string
  - name: chartDirectory
    type: string
  - name: githubOrg
    type: string
    default: FirelyTeam
  - name: appVersion
    type: string
    default: ''
  - name: prBaseBranch
    type: string
    default: main
  - name: prReviewers
    type: string
    default: ''

jobs:
- job: UpdateHelmChart
  displayName: Update Helm chart and create PR
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: helmCharts
  - task: PowerShell@2
    displayName: Update Chart.yaml and create PR
    inputs:
      targetType: inline
      script: |
        # Variables
        $appVersion = "${{ parameters.appVersion }}"
        $repoPath = "$(Build.SourcesDirectory)"
        $chartDirectory = "$repoPath/${{ parameters.chartDirectory }}"
        $chartFilePath = "$chartDirectory/Chart.yaml"
         if (-not (Test-Path -Path $chartFilePath)) {
            throw "Chart.yaml not found at path: $chartFilePath"
        }
        $branchName = "chore/update-appversion-$appVersion"
        $targetBranch = "${{ parameters.prBaseBranch }}"
        $githubOrg = "${{ parameters.githubOrg }}"
        $repoId = "${{ parameters.helmRepoId }}"
        $token = "$(git_token)"

        $reviewersString = "${{ parameters.prReviewers }}"
        $reviewers = $reviewersString -split '\s*,\s*'
        Write-Host "Reviewers: $reviewers"
        Write-Host "Using repo path: $repoPath"
        git config user.name $(git_user)
        git config user.email $(git_emailaddress)
        cd $chartDirectory
        git checkout -b $branchName
        $chartText = Get-Content -Raw -Path $chartFilePath

        # Extract current chart version
        if ($chartText -match 'version:\s*([0-9]+)\.([0-9]+)\.([0-9]+)') {
        $curMajor = [int]$Matches[1]
        $curMinor = [int]$Matches[2]
        $curPatch = [int]$Matches[3]
        } else {
        throw "Could not parse current chart version from Chart.yaml"
        }

        $newMajor = $curMajor
        $newMinor = $curMinor + 1
        $newPatch = 0
        $newChartVersion = "{0}.{1}.{2}" -f $newMajor, $newMinor, $newPatch

        Write-Host "Current chart version: $curMajor.$curMinor.$curPatch"
        Write-Host "New chart version: $newChartVersion"

        # Replace chart version and update existing appVersion
        $chartText = $chartText -replace '(?m)^version:\s*.*$', "version: $newChartVersion"
        # write appVersion with double quotes in Chart.yaml
        $chartText = $chartText -replace '(?m)^appVersion:\s*.*$', ('appVersion: "{0}"' -f $appVersion)

        # Write updated Chart.yaml
        Set-Content -Path $chartFilePath -Value $chartText -Encoding UTF8

        git add $chartFilePath
        git commit -m "chore: update appVersion to $appVersion"

        # ----------------------------------------
        # Secure GitHub authentication (no token in URL)
        # ----------------------------------------
        git remote set-url origin https://github.com/$githubOrg/$repoId
        git config credential.helper store

        $cred = "https://$(git_user):$(git_token)@github.com"
        Set-Content -Path "$env:USERPROFILE\.git-credentials" -Value $cred -Encoding ASCII

        Write-Host "WARNING: Force-pushing branch $branchName to origin. This will overwrite any existing branch with the same name."
        git push origin $branchName --force     

        # -----------------------------
        # Create Pull Request
        # -----------------------------
        $body = @{
          head  = $branchName
          base  = $targetBranch
          title = "chore: update appVersion to $appVersion"
          body  = "This PR was created automatically by Azure Pipeline."
        } | ConvertTo-Json

        $headers = @{
          Authorization = "token $token"
          "User-Agent" = "AzurePipeline"
          "Content-Type" = "application/json"
        }

        $url = "https://api.github.com/repos/$githubOrg/$repoId/pulls"

        Write-Host "Creating PR via: $url"

        try {
            $response = Invoke-RestMethod -Uri $url -Headers $headers -Method POST -Body $body
            $prNumber = $response.number
            Write-Host "PR created: $($response.html_url)"
        } catch {
            if ($_.Exception.Response.StatusCode -eq 422) {
                Write-Host "PR may already exist for branch $branchName"
                throw
            }
            throw
        }
        # -----------------------------
        # Add reviewers
        # -----------------------------
        if ($reviewers.Count -gt 0) {
            Write-Host "Adding reviewers: $reviewers"

            $reviewersBody = @{
                reviewers = $reviewers
            } | ConvertTo-Json

            $reviewerUrl = "https://api.github.com/repos/$githubOrg/$repoId/pulls/$prNumber/requested_reviewers"

            Invoke-RestMethod -Uri $reviewerUrl -Headers $headers -Method POST -Body $reviewersBody
            Write-Host "Reviewers added."
        } else {
            Write-Host "No reviewers specified."
        }

